services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - postgres
    networks:
      - network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-import.json
    ports:
      - ${KC_PORT}:${KC_PORT}
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    depends_on:
      - postgres
    networks:
      - network
    volumes:
      - ./keycloak/realm-import.json:/opt/keycloak/data/import/realm-import.json

volumes:
  postgres-data:

networks:
  network: